#!/usr/bin/env bash
set -euo pipefail

QATS="${QATS:-/mlx_devbox/users/quyanyi/playground/QATs}"

EXP="${EXP:-recipe_resume10_paramsinlate_ckpt3_aoq098_core71_100upd_gate_20260708}" \
LOG="${LOG:-/mlx_devbox/users/quyanyi/playground/train_recipe_resume10_paramsinlate_ckpt3_aoq098_core71_100upd_gate_20260708.log}" \
MASTER_PORT="${MASTER_PORT:-31358}" \
RESUME="${RESUME:-/mlx_devbox/users/quyanyi/playground/qat_public_repro/recipe_resume10_paramsinlate_ckpt2_250upd_gate_20260708/checkpoint-3.pth.tar}" \
START_EPOCH="${START_EPOCH:-3}" \
EPOCHS="${EPOCHS:-4}" \
SCHEDULER_EPOCHS="${SCHEDULER_EPOCHS:-4}" \
LR="${LR:-1.0e-5}" \
MIN_LR="${MIN_LR:-5.0e-6}" \
QUANT_LR_MULTIPLIER="${QUANT_LR_MULTIPLIER:-2}" \
PRE_QAT_FEATURE_RECON_UPDATES="${PRE_QAT_FEATURE_RECON_UPDATES:-0}" \
VARIATION_TRUST_WEIGHT="${VARIATION_TRUST_WEIGHT:-0}" \
TEACHER_FEATURE_OUTPUT_WEIGHT="${TEACHER_FEATURE_OUTPUT_WEIGHT:-0}" \
AOQ_EXPLORE_SCALE_RATIO="${AOQ_EXPLORE_SCALE_RATIO:-0.98}" \
AOQ_EXPLORE_LAYERS="${AOQ_EXPLORE_LAYERS:-features.7.1.attn.proj,features.7.1.mlp.fc2}" \
AOQ_EXPLORE_START_UPDATE="${AOQ_EXPLORE_START_UPDATE:-0}" \
AOQ_EXPLORE_END_UPDATE="${AOQ_EXPLORE_END_UPDATE:-100}" \
QUANT_ONLY_START_EPOCH="${QUANT_ONLY_START_EPOCH:-3}" \
TRAINABLE_POLICY="${TRAINABLE_POLICY:-params_in_layers}" \
TRAINABLE_POLICY_FREEZE_ACT_EXCEPT_LAYERS="${TRAINABLE_POLICY_FREEZE_ACT_EXCEPT_LAYERS:-features.5.5,features.7.1}" \
SAVE_STEP_CHECKPOINTS="${SAVE_STEP_CHECKPOINTS:-1}" \
STEP_CHECKPOINT_INTERVAL="${STEP_CHECKPOINT_INTERVAL:-100}" \
STEP_CHECKPOINT_WARMUP_UPDATES="${STEP_CHECKPOINT_WARMUP_UPDATES:-100}" \
MAX_STEP_CHECKPOINTS_TO_SAVE="${MAX_STEP_CHECKPOINTS_TO_SAVE:-1}" \
MAX_TRAIN_UPDATES="${MAX_TRAIN_UPDATES:-100}" \
bash "${QATS}/tmp_scripts/run_resume10_prerecon_vartrust_gate_20260707.sh"
